project_id = "ovbzoxwwurklwawdvudf"

[functions.vey-generate]
verify_jwt = false
entrypoint = "./functions/vey-generate/index.ts"

[functions.vey-refine]
verify_jwt = false
entrypoint = "./functions/vey-refine/index.ts"
