project_id = "mxrgdcvmxzhocbdhtlhg"

[functions.designly-v3-agent]
verify_jwt = true
entrypoint = "./functions/designly-v3-agent/index.ts"

[functions.designly-v3-refine]
verify_jwt = true
entrypoint = "./functions/designly-v3-refine/index.ts"

[functions.designly-huginn]
verify_jwt = false
entrypoint = "./functions/designly-huginn/index.ts"

[functions.designly-image]
verify_jwt = true
entrypoint = "./functions/designly-image/index.ts"

[functions.designly-video]
verify_jwt = true
entrypoint = "./functions/designly-video/index.ts"

[functions.vey-images]
verify_jwt = true
entrypoint = "./functions/vey-images/index.ts"

[functions.designly-form-submit]
verify_jwt = false
entrypoint = "./functions/designly-form-submit/index.ts"

[functions.admin-control]
verify_jwt = true
entrypoint = "./functions/admin-control/index.ts"
